return {
    dashboard = "dashboard",
    outline = "Outline",
    nvimtree = "NvimTree",
    noice = "noice",
    notify = "notify",
    dapui = {
        "dapui_watches",
        "dapui_breakpoints",
        "dapui_scopes",
        "dapui_console",
        "dapui_stacks",
        "dap-repl",
    },
    go = "go",
    lua = "lua",
    javascript = "javascript",
    typescript = "typescript",
    jsx = "javascriptreact",
    tsx = "typescriptreact",
    html = "html",
    webc = "webc",
}
