return {
    arduino = "arduino",
    c = "c",
    cpp = "cpp",
    css = "css",
    dapui = {
        "dap-repl",
        "dapui_breakpoints",
        "dapui_console",
        "dapui_scopes",
        "dapui_stacks",
        "dapui_watches",
    },
    dashboard = "dashboard",
    go = "go",
    html = "html",
    javascript = "javascript",
    json = "json",
    jsx = "javascriptreact",
    lua = "lua",
    noice = "noice",
    notify = "notify",
    nvimtree = "NvimTree",
    outline = "Outline",
    tsx = "typescriptreact",
    typescript = "typescript",
    webc = "webc",
}
