-- Generate comment for current line
vim.keymap.set("n", "<Leader>g", function()
	vim.cmd("DogeGenerate")
end)

-- Interactive mode comment todo-jumping
vim.keymap.set("n", "<C-n>", function()
	vim.cmd("call doge#comment#jump('forward')", { noremap = true, silent = true })
end)
vim.keymap.set("n", "<C-p>", function()
	vim.cmd("call doge#comment#jump('backward')", { noremap = true, silent = true })
end)
vim.keymap.set("i", "<C-n>", function()
	vim.cmd("call doge#comment#jump('forward')", { noremap = true, silent = true })
end)
vim.keymap.set("i", "<C-p>", function()
	vim.cmd("call doge#comment#jump('backward')", { noremap = true, silent = true })
end)
vim.keymap.set("x", "<C-n>", function()
	vim.cmd("call doge#comment#jump('forward')", { noremap = true, silent = true })
end)
vim.keymap.set("x", "<C-p>", function()
	vim.cmd("call doge#comment#jump('backward')", { noremap = true, silent = true })
end)
