return {
    require("plugins.utils.harpoon"),
    require("plugins.utils.live-server"),
    require("plugins.utils.nvim-tree"),
    require("plugins.utils.telescope"),
    require("plugins.utils.undotree"),
    require("plugins.utils.annotations-generators"),
    require("plugins.utils.which-key"),
    require("plugins.utils.auto-session"),
    -- require("plugins.utils.vim-rooter"),
    require("plugins.utils.qf-helper"),
    require("plugins.utils.goto-breakpoints"),
    require("plugins.utils.global-note"),
    require("plugins.utils.outline"),
}
