$schema: "https://json.schemastore.org/clangd.json"

CompileFlags:
  Add: ["-Wall", "-Wextra", "-Werror"]

---
If:
  PathMatch: .*\.h
CompileFlags:
  Add: ["-xc-header"]

---
If:
  PathMatch: .*\.c
CompileFlags:
  Add: ["-std=c18", "-xc"]
